# -*- mode: snippet -*-
# name: Hook Theme
# key: hook_theme
# --
/**
 * Implements hook_theme().
 *
 * TODO (`(getenv "USER")`): Add documentation.
 */
function `(file-name-nondirectory (file-name-sans-extension (buffer-file-name)))`_theme($existing, $type, $theme, $path) {
  return array(
    '`(file-name-nondirectory (file-name-sans-extension (buffer-file-name)))`_$1' => array(
      '${2:variables}' => array($0),
    ),
  );
}